---
title: "Test Quarto Website"
---

# Introduction

This is a tutorial for documenting research workflows using Quarto and RStudio. These protocols were developed in the context of systematic, biogeographic, and species delimitation studies using both morphometric and genetic data sets, but they could be employed for any research program, especially those that involve statistical analyses in R. We will perform a couple of analyses to illustrate some features of the documentation but this is not a tutorial on statistical analysis, rather it is an attempt to impart skills to document and share detailed workflows. The tutorial will assume some basic familiarity with statistical analysis and graphics in R.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

## Outline

-   Create a GitHub repository.

-   Create a new R project and Quarto website within R studio.

-   Create an R environment.

-   Edit the Quarto website settings to create pages documenting your workflows

-   Include narrative, textual information and interactive code.

-   Upload to GitHub repository.

# Create a GitHub repository

## Create a GitHub account

Go to <https://github.com> and create an account.

You should now have a dashboard with your user name and various options for customizing your GitHub dashboard, including options for creating a profile image, and links to various settings including options for creating new repositories.

## Create a GitHub repository

Select `Repositories` from the top menu on your dashboard on [github.com](https://github.com). This will take you to another page with a list of your repositories. You can create a single webpage for each GitHub repository.

Select the `New` button to create a new repository.

Enter an informative name in the `Repository name *` field along with a brief description in the `Description` field.

Choose `Public` from the dropdown menu for the `Choose visibility *` option under `Configuration`.

Click the toggle to `On` in the `Add README` option to generate an informative description of the repository. This should be a longer more detailed description than what is entered in the `Description` field.

Leave the `Add .gitignore` and `Add license` field to the default settings.

Click the `Create repository` button.

## Edit the README.md file

You will now see the dashboard for your repository. All that will be in the repository for now is the `README.md` file. You may edit the contents of `README.md` in GitHub by clicking on it and clicking the `Edit` button. After you are finished editing the `README.md` file click `Commit changes....` You can enter some brief description of the change if you like. Make sure the `Commit directly to main branch` option is selected and click `Commit change`. This will return you back to the main dashboard for the repository.

## Edit the repository settings

Select `Settings` from the menu bar across the top of the page. The repository name should appear in the top field. Do not rename the repository. Also the `Default branch` field should read `main`.

On the left menu select `Pages` to set up your html webpage for this repository. This will take you to the settings for GitHub Pages. The `Source` option should read `Deploy from a branch` and for the `Branch` option select `main` from the dropdown menu and `/docs`. Click the `Save` button.

You now have a working GitHub directory and you are ready to deploy your workflow documentation and analyses. Continue to the next stage.

# Create a new R project and Quarto website within R studio

You should have [R](https://www.r-project.org/), [RStudio](https://posit.co/download/rstudio-desktop), and [Quarto](https://quarto.org/) installed on your computer. You can conveniently install both the latest version of R and RStudio from the [RStudio website](https://posit.co/download/rstudio-desktop).

Create a directory for your project on your computer.

Open RStudio and go to the `File` menu and select `New Project`. This will take you to the `New Project Wizard` in RStudio. Select `New Directory`.

After choosing `New Directory` you will see a list of project types. Select `Quarto Website`.

Click the `Browse` button and navigate to the directory you created specifically for this project. Name the project directory. Select the check boxes for the `Create a git repository`, `Use renv with this project`, and `Use visual markdown editor`.

Now click on the `Create Project` button.

# Create an R environment

Working with an environment is a useful means to maintain consistency within an analysis such that the same package versions are used across sessions. If you selected the `Use renv with this project` when you initially set up the project in RStudio, congratulations, you do not have to do anything else. Your project will be running in its own dedicated environment. Remember that you will need to install packages into the research environments for each project you are working on as they will be stored in project-specific libraries. If you get a message during the creation of your project to install the `renv` package then add that package by following the prompts.

# Edit the Quarto website settings

You should now see your RStudio project. Open all the panes by clicking on `View`, then `Panes`, and `Show All Panes` if all the working panes are not visible. The source pane should be in the upper left quadrant of your screen. This is where you will enter text, images, and code to create your document. For editing your documents in the source pane you should choose the `Visual` editor option in the menu at the top of the source pane.

There are a number of other options here for editing text including bold (**`B`**), italics (*`I`*), and code (`</>`) selections for text. There is also a drop down menu beginning with `Normal` where you may select from either normal font for text or from a number of headings, which will create an outline of the document in the column on the right side of the source pane based on the headings. After this there are options for creating lists, inserting links and images, formatting text, and dropdowns for inserting code blocks, tables, citations, and other information. The menu bar above these options has choices for saving the file (a disc icon), rendering files to html documents, and running code blocks.

The source pane will initially will contain only two tabs corresponding to the two files created with the Quarto webpage. These will be titled `index.qmd` and `_quarto.yml`. Adding additional `qmd` files will ad additional pages to the webpage and additional tabs in the source pane.

Select the `_quarto.yml` file and in the project information, under `type: website`, type the following.

```         
output-dir: docs
```

Be sure to click the `Save` icon on the file tab after making changes.

This will create a `docs` folder with the rendered files created by Quarto which will be uploaded to the GitHub repository.

# Include narrative, textual information, and interactive code

## Create a written narrative

This is the fun part. Be creative in generating the narrative of the workflow but most importantly be detailed in your instructions. The goal is that a reader should be able to follow your instructions and replicate your results exactly. There will be people with varying skill sets and experience reading your documentation, including sometimes students with very little background in computing or using a primarily command line interface. Write your workflows with those people in mind.

## Render your results

Save results once a file has been updated by clicking on the save icon in the source pane menu, it appears as a computer disc icon.

Once your edits are completed then render the page by clicking on the `Render` selection in the source pane menu. Depending on the complexity of your page and the amount of code needed to run this can take a little while. Rendering will create a copy of your webpage in html format stored in the `docs` folder.

# Upload to GitHub repository

## Authenticate your GitHub remote repository

You need to specify where your files will be sent. Check to determine if there is a remote repository site set up by entering this command in the terminal.

```         
git remote -v
```

If there is no output from this command then you need to set up the remote repository.

If you use the following code you will be asked for a username and password for your GitHub account. Remember throughout these instructions where you see `<USERNAME>` replace with your GitHub username and where you see `<REPOSITORY_NAME>` replace with the name you gave your GitHub repository.

``` bash
git remote set-url origin github.com/<USERNAME>/<REPOSITORY_NAME>.git
```

However, despite getting prompts to enter a username and password, authenticating a remote repository on GitHub is no longer supported from command prompts in the terminal, so you will likely see the prompts but get an error message. Instead return to your GitHub account and create a token for your GitHub site.

Go to your dashboard for your GitHub account. Go to the `user navigation window` by clicking on your user icon in the top right corner. Select `Settings` from that menu. A list of menu options should be listed on the left side of your window. Scroll down and select the `< > Developer` settings option. Click on `Personal access tokens` on the left, from the drop down select `Tokens (classic)` and click the `Generate new token` button and from that drop down select `Generate new token (classic)`. You should now be on a new page that provides options for choosing the settings for the access token. Give your access token a name and from the token options select the `repo` and `workflow` check boxes. Now click on `Generate token`.

You have now created a security access token that may be used to upload changes to your GitHub site. The token is a long series of random characters like this (don't worry, this isn't an active token!)

```         
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
```

Copy the token. You will not be able to go back and see it later. There is an icon beside it you can click on to copy.

There needs to be a secure place to store the token. We need to keep this token secret else errors will pop up when trying to push data to the GitHub site later so we will save the token in a `.env` file that will be ignored along with other files listed in a `.gitignore` file. Create a txt file in your text editor. The only contents of that file should be as follows, replacing \<YOURTOKEN\> with the token created on the GitHub site.

```         
GITHUB_TOKEN=<YOURTOKEN>
```

Update Your remote URL setting in the terminal with this token. Replace \<YOUR_USERNAME\> with the username for your GitHub account and \<YOUR_TOKEN\> with the security token created on the GitHub site and matching the token in the `.env` file.

```         
git remote set-url origin https://<YOUR_USERNAME>:<YOUR_TOKEN>@github.com/
<YOUR_USERNAME>/<REPOSITY_NNAME>.git
```

Install the `dotenv` package. You may do this in R by selecting `Tools`, followed by `Install packages...` and then search for `dotenv` and click on `Install`. Once you have the `dotenv` package installed load the package library and identify which file contains the GitHub token with the following commands in R.

```{r}
library(dotenv)
load_dot_env()
github_token <- Sys.getenv("GITHUB_TOKEN")
```

## Configure your GitHub repository

When you are ready to upload your changes to your GitHub website go to your terminal by selecting the `Terminal` tab in the lower left pane in RStudio.

Make certain that the name of the default branch is `main` in your GitHub `Pages` settings (see \[**Create a GItHub repository**\]).

```         
git config --global init.defaultBranch main
```

Add your user email and GitHub username to your GitHub configuration.

```         
git config --global user.email "youremail@gmail.com"
git config --global user.name "yourusername"
```

Verify that you are in the correct directory and check the status of your repository.

```         
git status
```

## Add files to the GitHub repository

To add new files or other changes the files need to be staged. Remember to add the period at the end of this command as that indicates changes are being added to the current directory.

```         
git add .
```

Commit the staged changes and include a brief descriptive message. The first commit of data you may just call `Initial commit`. I sometimes use the date and time for descriptions of subsequent commits.

```         
git commit -m "Initial commit"
```

After this commit you should see a list of files that were updated.

Now, you want to send or "push" these changes to the Github repository. First, check and make sure you have saved the right remote repository.

```         
git remote -v
```

After confirming your remote repository conduct a pull from the repository to sync any changes that may exist on the repository that have not been saved locally. This is often unnecessary if you are the sole agent pushing changes to the repository but it is a good habit regardless.

```         
git pull origin main
```

Next push your local changes to the GitHub repository. Make sure the location is `main`.

```         
git push origin main
```

# Render as a pdf

There are many benefits to distributing your workflows and data analyses through an html site including interactivity and ease in copying code. You may readily link html sites in the supplementary data accompanying a manuscript, or in the manuscript itself. However, html sites need to be hosted somewhere, like GitHub, and while these resources are farily accessible, an author may prefer to share protocols, workflows, and data analyses in ways that do not require web hosting. Rendering a Quarto file as a pdf is an option in this case.

```         
quarto render <YOUR _FILE_NAME>.qmd --to pdf
```
